name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v1

      - name: Run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

      - name: Build and test with coverage
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
